# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs  sampler using Rcpp
#' @param sigma the sigma value
#' @param x0 the start point
#' @param N the number of circles
#' @return a matrix of results
#' @export
Metropolis <- function(sigma, x0, N) {
    .Call('_StatComp20091_Metropolis', PACKAGE = 'StatComp20091', sigma, x0, N)
}

